title: Portfolio
description: Hey! My name is Josh and I am a freshman at the University of Michigan. I am interested in quantitative finance, theoretical CS, and startups. I hope to explore health disparities driven by research at the intersections of medicine and technology.
baseurl: ""
url: "https://www.joshveergrewal.com/"